config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :sports_ipps, :collection => { :recent => :get }

  map.resources :sports_ipp_medias, :member => {:package_uploaded => :get}

  map.resources :sports_ipp_statuses

  map.resources :special_schedule_logs

  map.resources :parts

  map.resources :special_schedule_settings

  map.resources :generate_status_lines

  map.resources :generate_status_settings

  map.resources :dynamic_special_medias

  map.resources :dynamic_special_logos

  map.resources :automated_dynamic_special_fields

  map.resources :automated_dynamic_specials, :collection => {:duplicate => :get, :demo_image => :get, :archive_multiple => :delete, :report => :get, :placing => :get}, :member => {:archive => :delete, :export => :get}

  map.resources :template_field_joins

  map.resources :dynamic_special_templates

  map.resources :dynamic_special_fields

  map.resources :dynamic_special_image_specs

  map.resources :clipsources

  map.resources :on_demand_schedulings

  map.resources :channel_on_demands

  map.resources :on_demand_files

  map.resources :services

  map.resources :on_demands, :member => {:add_promo => :get, :edit_on_demand => :get, :delete_promo => :delete, :create_promo => :get, :unlink_promo => :delete, :show_on_demand => :get }

  map.resources :channel_special_previews

  map.resources :special_previews, :collection => { :recent => :get }

  map.resources :diva_polls

  map.resources :diva_logs

  map.resources :diva_tasks

  map.resources :diva_settings

  map.resources :diva_datas

  map.resources :diva_statuses

  map.resources :trailer_house_number_prefixes

  map.resources :channel_trailers

  map.resources :trailer_files

  map.resources :trailers, :collection => {:delete_all_not_available => :delete, :diva_media_search => :get, 
                                            :diva_workflow => :get, :delete_diva_references => :delete,
                                            :diva_workflow_update => :get } #, :member => {:diva_media_search => :get}

  map.resources :trailer_tab_settings

  map.resources :exception_lists

  map.resources :dynamic_specials, :collection => { :duplicate => :get, :delete_multiple => :delete }
  
  map.resources :special_fields
  
  map.resources :series_idents, :collection => {:destroy_all => :get, :add_dummy => :get }, 
                                :member => {:edit_from_title => :get, :edit_from_comparison => :get, 
                                            :edit_series => :get, :update_press_series => :get}

  map.resources :cross_channel_priorities

  map.resources :aspects

  map.resources :statuses

  map.resources :promos,  :collection => { :last_use => :get, :add_all_series_idents => :get, :delete_all_series_idents => :delete }, 
                          :member => {:add_series_idents => :get }

  map.resources :media_types

  map.resources :priorities

  map.resources :series_numbers

  map.resources :series_numbers

  map.resources :schedule_comparisons, :member => {:keep_series => :get, :delete_house => :get, :add_eidr => :get }

  map.resources :schedule_files

  map.resources :schedule_lines

  map.resources :schedule_tab_settings

  map.resources :countdown_ipps

  map.resources :media_files, :collection => { :unready => :get, :last_use => :get, :move_2012 => :get, :recent => :get }, :member => {:resize => :get, :crop => :post, :queue => :get}

  map.resources :media_folders

  map.resources :commons

  map.resources :jpegs

  map.resources :jpeg_folders

  map.resources :bugs

  map.resources :press_filenames

  map.resources :playlist_filenames

  map.resources :channels

  map.resources :languages

  map.resources :houses, :collection => {:add_all_series_ident => :get },
                         :member => {:new_from_comparison => :get}

  map.resources :titles, :member => {:new_series => :get, :add_promo => :get, :delete_promo => :delete, :search_promo => :get, 
                                     :edit_title => :get, :create_series_ident => :get, :delete_series_ident => :delete,
                                     :change_series_ident => :get, :choose => :get, :edit_title_house_or_series_known => :get, 
                                     :update_press_title => :get, :new_from_press => :get, :clone => :get, :auto_add_local_discrepancy_multiple => :get,
                                     :auto_add_local_discrepancy => :get, :stored_local => :get, :update_multiple_press_title => :get}

  map.resources :ignores

  map.resources :comparisons, :member => {:add_series =>:get, :add_title_series => :get, :add_local_title => :get, :add_eidr_to_house => :get }
  
  map.resources :press_lines, :collection => { :priority => :get, :cross_channel_selection => :get, :schedule => :get, 
    :random => :get, :add_random => :get, :remove_all_specials => :get, :part => :get, :add_part => :get }

  map.resources :playlist_lines

  map.resources :playlist_position_settings

  map.resources :press_tab_settings

  map.resources :uploads
  
  map.resources :previews

  map.resources :preview_jpegs  
  

  

  map.root :controller => "previews"

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/title.rb
class Title < ActiveRecord::Base
  
  has_many :houses, :dependent => :delete_all
  has_many :promos, :dependent => :delete_all
  has_many :series_idents, :dependent => :delete_all
  has_many :cross_channel_priorities, :dependent => :delete_all
  
  validates_presence_of :english
  default_scope :order => :english
  
  attr_accessor :source
  attr_accessor :channel
  attr_accessor :schedule_comparison_id
  attr_accessor :press_line_id
  attr_accessor :language
      
  def self.search(search, page)
    if search
      paginate  :per_page => 12, :page =>page,
                :conditions => ['english LIKE ?', "%#{search}%"]
    else
      paginate  :per_page => 12, :page =>page
    end
  end
  def self.search_eidr(search, page)
    if search
      mum = paginate(:per_page => 12, :page =>page,
                :joins => :series_idents,
                :conditions => ['series_idents.eidr LIKE ?', "%#{search}%"])
      mum.uniq
    else
      paginate  :per_page => 12, :page =>page
    end
  end
  
  def self.search_types
    ['English Title','EIDR']
  end

    
  def eop_display
    if eop
      "Own"
    else
      "None"
    end
  end
  
  def eop_boolean
    if eop
      "True"
    else
      "False"
    end
  end   
  
  def has_language?(language_name)
    case language_name
    when "Danish"
      not danish.blank?
    when "Swedish"
      not swedish.blank?
    when "Hungarian"
      not hungarian.blank?
    when "Norwegian"
      not norwegian.blank?
    else
      false
    end
    
  end
  
  def local_title(language_name)
    case language_name
    when "Danish"
      danish
    when "Swedish"
      swedish
    when "Hungarian"
      hungarian
    when "Norwegian"
      norwegian
    else
      ""
    end
  end
  
  def add_promo(promo_id)
    p = Promo.find(promo_id)
    num = 0
    if p
      series_idents.each do |s|
        found = false
        s.promos.each do |pr|
          found = true if pr == p
        end
        s.promos << p unless found
        num += 1 unless found
      end
      if num == 0
        'Already added. '
      elsif num ==1 
        'Added to 1 series ident. '
      else
        'Added to ' + num.to_s + ' series idents. '
      end
    else
      'Promo not found. '
    end
  end
  
  def set_discrepancy(comparison)
    english = comparison.original_title
    case comparison.channel.language_name 
    when 'Danish'
      danish = danish_title
    when 'Swedish'
      swedish = danish_title
    when 'Hungarian'
      hungarian = danish_title
    when 'Norwegian'
      norwegian = danish_title
    end
  end

  def self.add_series_and_house(comparison_id, comparison_type, eop)
    if comparison_type == 'schedule_comparison'
      comparison = ScheduleComparison.find_by_id(comparison_id)
    else
      comparison = Comparison.find_by_id(comparison_id)
    end
	
    notice = ''
    added = 0
    title_added =0
    house_added = 0
    promo_added = 0
    local_added = 0
    issues = 0
    title_issues = 0
    house_issues = 0
    local_issues = 0
    success = false
    continue = false
    create_title = false
    if comparison
      code = comparison.comparison_code.to_sym
      
      case code
      when *[:not_db_no_match_contained, :not_db_no_match]
        #does house number already exist from other route
        house = House.find_by_house_number(comparison.house_number)
        if house.nil?
          eidr = SeriesIdent.find_by_eidr(comparison.eidr)
          if !eidr.nil?
            #This has an already existing eidr
            eidr_title = eidr.title
            if eidr_title.english == comparison.original_title && eidr_title.local_title(comparison.channel.language.name) == comparison.local_title
              #The eidr is the same title. No need to create a new one
              continue = true
            else
              create_title = true
            end
          else
            #eidr is null but lets see if the title already exists
            if !find_by_english(comparison.original_title)
              create_title = true
            end
          end
          if create_title
            continue = true
            @title = Title.new
            @title.english = comparison.original_title
            if eop
              @title.eop = true
            else
              @title.eop = false
            end
            if @title.save
              title_added += 1
            else
              @title.errors.each do |e|
                notice += e.to_s.capitalize + ". "
                title_issues += 1
              end
            end
          end
        else
          notice += "Possible same programme ticked more than once as house number already present: #{comparison.house_number} - #{comparison.original_title}. "    
        end
      else
        continue = true
      end
      
      if continue
        case code
        when *[:not_db_no_series, :not_db_no_series_local_blank, :not_db_no_match_contained, :not_db_no_match, :not_db_local_blank]
          @title = find_by_english(comparison.original_title)
          case code
          when *[:not_db_no_series_local_blank, :not_db_no_match_contained, :not_db_no_match, :not_db_local_blank]
            stats = set_local_title(comparison.local_title, comparison.channel)
            local_added += stats[:added]
            local_issues += stats[:issues]
            notice += stats[:notice]
            if stats[:do_save]
              @title.save
            end
          end
          press = PressLine.find(comparison.press_id)
          logger.debug "1PPPP"
          logger.debug press
          s = SeriesIdent.find_by_title_id_and_year_number(@title.id, press.year_number)
          logger.debug s
          if s
            if s.eidr.blank? 
              s.eidr = press.eidr
            elsif s.eidr != press.eidr
              s = SeriesIdent.new
              s.update_info(@title.id, comparison.press_id)
            end
          else
            s = SeriesIdent.new
            s.update_info(@title.id, comparison.press_id)
          end
          if s.save
            added += 1
            stats = House.add_from_comparison(comparison_id, comparison_type)
            success = stats[:success]
            house_added += stats[:added]
            house_issues += stats[:issues]
            notice += stats[:notice]
            promo_added += stats[:promo_added]
          else
            s.errors.each do |e|
              notice += e.to_s.capitalize + ". "
              issues += 1
            end
          end
        else
          notice += 'Wrong type of add'
          issues += 1
        end
      end
    end
    {:added => added, :house_added => house_added, :issues => issues, :house_issues => house_issues, :promo_added => promo_added,
      :local_added => local_added, :local_issues => local_issues, :title_added => title_added, :title_issues => title_issues,
      :notice => notice, :success => success}  
  end  
  
  def self.add_local_title(comparison_id, source)
    if source == 'schedule_comparison'          
      comparison = ScheduleComparison.find_by_id(comparison_id)
    else
      comparison = Comparison.find_by_id(comparison_id)
    end
    if comparison.series_ident != ""
      s = SeriesIdent.find_by_number(comparison.series_ident)
    else
      if comparison.eidr != ""
        s = SeriesIdent.find_by_eidr(comparison.eidr)
      end
    end
    if s
      code = comparison.comparison_code.to_sym 
      case code
      when *[:in_db_local_blank, :not_db_local_blank]
      	if s.eidr.blank?
      		s.eidr = comparison.eidr
      		s.save
				end
        @title = s.title
        if @title
          stats = set_local_title(comparison.local_title, comparison.channel)
          if stats[:do_save]
            @title.save
          end
          stats
        else
          {:added => 0, :issues => 1, :notice => 'Cannot find title'}
        end
      else
        {:added => 0, :issues => 1, :notice => 'Cannot find record'}
      end
    else
      {:added => 0, :issues => 1, :notice => 'Cannot find title'}
    end
  end

  def self.add_local_title_and_house(comparison)
    if comparison.eidr != ""
      s = SeriesIdent.find_by_eidr(comparison.eidr)
    else
      if comparison.series_ident != ""
        s = SeriesIdent.find_by_number(comparison.series_ident)
      end
    end
    if s
      code = comparison.comparison_code.to_sym 
      case code
      when *[:in_db_local_blank, :not_db_local_blank]
      	if s.eidr.blank?
      		s.eidr = comparison.eidr
      		s.save
				end
        @title = s.title
        if @title
          stats = set_local_title(comparison.local_title, comparison.channel)
          #{:added => added, :issues => issues, :notice => notice, :do_save => do_save}
          if stats[:do_save]
            @title.save
            #Now add the house
            house = House.find_or_create_by_house_number(comparison.house_number)
            house.series_ident = s
            house.house_number = comparison.house_number
            house.title = s.title
            if house.save
              stats[:house_added] = 1
            else
              house.errors.each_full do |err|
                if err.upcase != "HOUSE NUMBER  IS ALREADY IN THE SYSTEM"
                  logger.debug "============>" + err.upcase
                  stats[:issues] += 1
                  stats[:notice] += err + ". "
                end
              end
            end
          end
          stats
        else
          {:added => 0, :issues => 1, :notice => 'Cannot find title'}
        end
      else
        {:added => 0, :issues => 1, :notice => 'Cannot find record'}
      end
    else
      {:added => 0, :issues => 1, :notice => 'Cannot find title'}
    end
  end

  def self.add_from_comparison(comparison)
    notice = ''
    added = 0
    house_added = 0
    issues = 0
    house_issues = 0
    success = false
    if not comparison[:found]

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/promos/_basic_entry.html.erb
<%= calendar_date_select_includes "custom", :locale=>'uk' %>
<p>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :description %><br />
  <%= f.text_field :description %>
</p>
<p>
  <%= f.label :first_use %><br />
	<%= f.calendar_date_select :first_use, {:month_year => :label, :minute_interval => 1} %>
</p>
<p>
  <%= f.label :last_use %><br />
	<%= f.calendar_date_select :last_use,  {:month_year => :label, :minute_interval => 1} %>
</p>

app/views/promos/_entry.html.erb
<%= render :partial => 'basic_entry', :locals => {:f => f} %>


<label><%= pluralize(@promo.series_idents.count, 'associated title')%></label><br/>

<%= link_to_function 'Hide/Show Associated Titles' do |page|
	page['associated-titles'].toggle()
end %>
<br/>

<% if @promo.series_idents.count > 6 %>
  <div id= 'associated-titles', style = 'display: none;'>
<% else %>
  <div id= 'associated-titles'>
<% end %>
  <% @promo.series_idents.each do |s| %>
    <p id = 'series_ident'>
      <%= render :partial => 'shared/associated', :locals => {:series_ident => s} %>
      <%= link_to 'Remove', { :controller => :promos, :action => :delete_series_ident,
                            :id => params[:id], :series_ident_id => s.id,  
                          :search => params[:search], :page => params[:page]},
                        :confirm => 'Are you sure?'%>
    </p>
  <% end %>
</div>

<label><%= pluralize(@promo.on_demands.count, 'associated On Demand title')%></label><br/>

<%= link_to_function 'Hide/Show Associated On Demand Titles' do |page|
	page['associated-od-titles'].toggle()
end %>
<br/>

<% if @promo.on_demands.count > 6 %>
  <div id= 'associated-od-titles', style = 'display: none;'>
<% else %>
  <div id= 'associated-od-titles'>
<% end %>
  <p id = 'series_ident'>
    <%= render :partial => 'shared/associated_on_demand', :locals => {:on_demands => @promo.on_demands} %>
  </p>
</div>


<%= link_to_function 'Toggle Title Search' do |page|
	page['search_title'].toggle()
end %>

app/views/promos/_media.html.erb
<% if promo.media_files.count > 0 %>

<table class = 'media_table' width = '90%'>
	<% if heading %>
	  <tr class = 'media' >
      <th>Name</th>
      <th>Filename</th>
      <th>Media Type</th>
		  <% if details %>
	      <th>Media folder</th>
	      <th>First use</th>
	      <th>Last use</th>
		  <% end %>
		  <th>Status</th>
		  <th></th>
		  <th></th>
		  <th></th>
		  <th></th>
    </tr>
	<% end %>

	<% promo.media_files.each do |media_file| %>
  	<% if media_file.has_audio %>
	  	<tr class = 'audio' >
	  <% else %>
	    <tr class = 'media' >
	  <% end %>
			<td width = '180' >
				<% if media_file.jpeg_exist? %>
				  <% if media_file.portrait? %>
					  <%= link_to image_tag(media_file.jpeg_url, :size => "60x108"), media_file_path(media_file, :source => source, :promo_id => promo, :upload => 'false') %>
					<% else %>
					  <%= link_to image_tag(media_file.jpeg_url, :size => "160x90"), media_file_path(media_file, :source => source, :promo_id => promo, :upload => 'false') %>
					<% end %>
				<% end %>
			</td>
			<td colspan = '3' width = '50%'>
				<b><%=h media_file.media_type.name unless media_file.media_type.nil?%> Name: </b><%=h media_file.name %><br/>
				<b>Filename: </b><%=h media_file.filename %><br/>
  			<% if details %>
    			<% if media_file.has_audio %>
    			  <b>Audio Filename: </b><%=h media_file.audio_filename %><br/>
   			  <% end %>
			  	<b>Folder: </b><%=h media_file.media_folder.folder unless media_file.media_folder.nil? %><br/>
			  	<b>First Use: </b><%=h media_file.first_use.to_s(:broadcast_datetime) unless media_file.first_use.nil? %><br/>
			  	<b>Last Use: </b><%=h media_file.last_use.to_s(:broadcast_datetime) unless media_file.last_use.nil? %><br/>
				<% end %>
				<div class = "<%= media_file.status_css %>"><b>Status: </b><%=h media_file.status.message unless media_file.status.nil?%></div>
			</td>
			<td><%= link_to 'Details', media_file_path(media_file, :source => source, :promo_id => promo, :upload => 'false')%></td>
			<td><%= link_to 'Upload', media_file_path(media_file, :source => source, :promo_id => promo, :upload => 'true')%></td>
			<td><%= link_to 'Edit', edit_media_file_path(media_file, :source => source, :promo_id => promo) %></td>
	    <td><%= link_to 'Destroy', media_file_path(media_file, :source => source, :promo_id => promo) , :confirm => 'Are you sure?',:method => :delete %></td>
		</tr>
	<% end %>
</table>

<% else %>
	<table><tr><td>No Clips or Stills created for this promo. 
		<%= link_to 'Add', promo_path(promo) %>
		</td></tr>
	</table>
<% end %>

app/views/promos/edit.html.erb
<h1>Editing Promo Media</h1>

<% form_for(@promo) do |f| %>
  <%= f.error_messages %>

  <%= render :partial => 'entry', :locals	=> {:f => f} 	%>

  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @promo %> |
<%= link_to 'Back', promos_path %>

<% if params[:search].nil? %>
	<div id ='search_title' , style = "display: none;" >
<% else %>
	<div id ='search_title'>
<% end %>

<h1>Programme Titles</h1>
<% form_tag edit_promo_path, :method =>'get' do %>
<p>
	<%= text_field_tag :search, params[:search]||@promo.first_english_title, :size => 45 %>
  <%= select_tag :search_type, options_for_select(@search_types, params[:search_type])%>
	<%= submit_tag "Search", :name => nil %>
</p>			
<% end %>
<%= render :partial => 'shared/titles', :locals => {:include_add => true } %>
</div>

app/views/promos/index.html.erb
<% content_for(:title) do%>
	Promo Media: MuVi2 Database
<% end %>

<p id = 'admin_link'>
	<%= link_to_function 'Admin' do |page|
			page.select('.admin').each { |a| a.toggle }
		end %>
</p>

<fieldset>
	<legend>Promo Media</legend>
		<% form_tag promos_path, :method =>'get' do %>
			<p>
				<%= text_field_tag :search, params[:search], :size => 45 %>
				<%= submit_tag "Search", :name => nil %>
			</p>
		<% end %>
		<% if params[:details] == 'true'%>
			<%= link_to 'Hide details', promos_path(:search => params[:search], :details => 'false')%>
		<% else %>
			<%= link_to 'Show details and images', promos_path(:search => params[:search], :details => 'true')%>
		<% end %>
</fieldset>

<br/>
<%= link_to 'New promo', new_promo_path %> | <%= link_to 'Promo Media not ready' , media_files_unready_path %> |
<%= link_to 'Promos past last use date', promo_past_last_use_path %>
<span class = 'admin', style = "display: none;"> |
<%= link_to 'Add series idents to all', add_all_series_idents_promos_path %> |
<%= link_to 'Delete all series idents',  delete_all_series_idents_promos_path, 
										:confirm => 'Are you really sure? This is a big change and will take some time.', 
										:method => :delete %><br/>
</span>

<%= will_paginate @promos %>

<table>
<% @promos.each do |promo| %>
	<tr>
	    <td><b><%=link_to(h(promo.name), promo) %></b></td>
		<td><table>
			<% promo.series_idents.each do |s|%>
				<% if params[:details] == 'true'%>
				<tr><td><i>Series Ident: <%= h s.full_description %></i></td>
					<td><i>Programme Title: <%= h s.title.english unless s.title.nil? %><br />
						   <%= h 'Title Description: ' + s.title.description unless s.title.nil?||s.title.description.blank? %></i></td></tr>
				<% else %>
					<tr><td><i>Series Ident: <%= h s.number %></i></td>
						<td><i>Programme Title: <%= h s.title.english unless s.title.nil? %></i></td></tr>
				<% end %>
			<% end %>
			</table>
		</td>
	    <td><%= link_to 'Details', promo %></td>
	 	<td class = 'admin', style = 'display: none;'><%= link_to 'Add Series Ident', add_series_idents_promo_path(promo) %></td>
	    <td><%= link_to 'Edit', edit_promo_path(promo) %></td>
	    <td><%= link_to 'Destroy', promo, :confirm => 'Are you sure?', :method => :delete %></td>
	</tr>
	<% if params[:details] == 'true'%>
		<tr>
			<td colspan = '6'><i><%=h 'Promo Descrption: ' + promo.description unless promo.description.blank? %></i></td>
		</tr>
		<tr>
			<td colspan = '6'><%= render :partial => 'media', :locals	=> {:promo => promo, :heading => false, 
				:details => false, :source => 'promo index'} %></td>
	<% end %>

<% end %>
</table>
<br/>

<%= will_paginate @promos %>

app/views/promos/last_use.html.erb
<% content_for(:title) do%>
	Promo Past Last Use: MuVi2 Database
<% end %>
<%= calendar_date_select_includes "custom", :locale=>'uk' %>

<% if Useful.date?(params[:last_use_date]) %>
<% 	last_use_display = params[:last_use_date]%>
<% else %>
<%	last_use_display = format_date_time(Date.today,"%B %e, %Y") %>
<% end %>
<% 	six_months_time = format_date_time(Date.parse(last_use_display).to_datetime.advance(:months => 6, :hours => 5),"%B %e, %Y %I:%M %p") %>
<fieldset>
	<legend>Promo Media</legend>
		<% form_tag promo_past_last_use_path, :method =>'get' do %>
			<p>
				<%= text_field_tag :search, params[:search], :size => 45 %>
				<%= submit_tag "Search", :name => nil %>
			</p>
		<%= calendar_date_select_tag :last_use_date, last_use_display, {:month_year => :label, :after_close => 'this.form.submit()'} %>
    <%= select_tag :media_type_display, options_for_select(@media_type_display, params[:media_type_display]),{:onchange => 'this.form.submit()'}%><br/>
		<% end %>
</fieldset>

<br/>

<%= will_paginate @promos %>


<% form_tag :action => :change_last_use do %>
<table>
	<tr>
		<th></th>
		<th>Name</th>
		<th>First Use</th>
		<th>Last Use</th>
	</tr>

	<% @promos.each do |promo| %>
		  <tr>
				<td><%= check_box_tag "promo_ids[]", promo.id, false , :class => 'fred' %></td>
		    <td><b><%=h promo.name %></b></td>
				<td><%=h promo.first_use.to_s(:broadcast_datetime) unless promo.first_use.nil?%></td>
				<td><%=h promo.last_use.to_s(:broadcast_datetime) unless promo.last_use.nil? %></td>
	
		    <td width = '50'><%= link_to 'Details', promo %></td>
		    <td width = '50'><%= link_to 'Edit', edit_promo_path(promo) %></td>
		    <td width = '50'><%= link_to 'Destroy', promo, :confirm => 'Are you sure?', :method => :delete %></td>
		  </tr>

	<% end %>
	</table>
	<br/>
	<%= will_paginate @promos %>


	<span class = 'info_text'>
		Set last use dates of selected promos and <br/>all media files associated with those promos	<br/>
	</span>
	<%= calendar_date_select_tag :new_last_use, six_months_time, {:size => '45', :month_year => :label, :time => true, :minute_interval => 1} %>
	<%= submit_tag "Add all checked", :confirm => "This will update the last use date on all the checked promos " +
																								"and all the media associated with those promos. \n\n" +
																								"This cannot be undone. \n\nAre you sure you want to do this?" %>

<% end %>

<span class = 'link_button'>
<%= link_to_function 'Check all', "$$('input.fred').each(function(checkbox) { checkbox.checked = true; });" %>
<%= link_to_function 'Uncheck all', "$$('input.fred').each(function(checkbox) { checkbox.checked = false; });" %>
</span>

app/views/promos/new.html.erb
<h1>New Promo Media</h1>

<% form_for(@promo) do |f| %>
  <%= f.error_messages %>

 <%= render :partial => 'basic_entry', :locals	=> {:f => f} 	%>
 <p id = "new_promo_message">
	There are no associated titles or series with this promo, yet <br />
	Click 'Create' and then a screen will appear that will allow you to add some. <br />
 </p>
 <%= f.submit 'Create' %>
<% end %>

<%= link_to 'Back', promos_path %>

app/views/promos/show.html.erb
<% content_for(:title) do%>
	Promo Media: MuVi2 Database
<% end %>
<% content_for(:refresh) do%>
  <meta http-equiv="refresh" content="20" />
<% end %>

<p>
  <label>Promo Name</label><br/>
  <%=h @promo.name %>
</p>

<p>
  <label>Description</label><br>
  <%=h @promo.description %>
</p>

<label><%= pluralize(@promo.series_idents.count, 'associated title')%></label><br/>

<%= link_to_function 'Hide/Show Associated Titles' do |page|
	page['associated-titles'].toggle()
end %>
<br/>

<% if @promo.series_idents.count > 6 %>
  <div id= 'associated-titles', style = 'display: none;'>
<% else %>
  <div id= 'associated-titles'>
<% end %>

  <% @promo.series_idents.each do |s| %>
    <p id = 'series_ident'>
      <%= render :partial => 'shared/associated', :locals => {:series_ident => s} %>
    </p>
  <% end %>
</div>

<label><%= pluralize(@promo.on_demands.count, 'associated On Demand title')%></label><br/>
<%= link_to_function 'Hide/Show Associated On Demand Titles' do |page|
	page['associated-od-titles'].toggle()
end %>
<br/>

<% if @promo.on_demands.count > 6 %>
  <div id= 'associated-od-titles', style = 'display: none;'>
<% else %>
  <div id= 'associated-od-titles'>
<% end %>
  <p id = 'series_ident'>
    <%= render :partial => 'shared/associated_on_demand', :locals => {:on_demands => @promo.on_demands} %>
  </p>

</div>

<table>
	<tr>
		<td><b>First Use</b></td>
		<td><%=h @promo.first_use.to_s(:broadcast_datetime)%></td>
		<td><b>Last Use</b></td>
		<td><%=h @promo.last_use.to_s(:broadcast_datetime)%></td>
	</tr>
</table>
<br/>
  <%= render :partial => 'media', :locals	=> {:promo => @promo, :heading => false, 
	:details => true, :source => 'promo'} %>
<p>	
	<%= link_to "Add Clip", :action => :add_media, :id => @promo, :media_type => :clip %> |
	<%= link_to "Add Clip with Audio", :action => :add_media, :id => @promo, :media_type => :clipaudio %> |
	<%= link_to "Add Still", :action => :add_media, :id => @promo, :media_type => :still %> |
	<%= link_to "Add Portrait Still", :action => :add_media, :id => @promo, :media_type => :portrait %>
</p>


<%= link_to 'Edit', edit_promo_path(@promo) %> |
<%= link_to 'Back', promos_path %>